blog/urls.py
from django.conf.urls import patterns, include, url
from . import views
from django.contrib import admin
# import blog.views as bv
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myblog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^index/$', views.index),
    url(r'^article/(?P<article_id>[0-9]+)$',views.article_page,name='article_page'),
    url(r'^edit/(?P<article_id>[0-9]+)$',views.edit_page,name='edit_page'),
    url(r'^edit/action$',views.edit_action,name='edit_action')
)

myblog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
# import blog.views as bv
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myblog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls',namespace='blog')),
)

blog/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
	title=models.CharField(max_length=32,default='Title')
	content=models.TextField(null=True)
	
	def __unicode__(self):
		return self.title

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
# Create your views here.
def index(request):
	articles=models.Article.objects.all()
	return render(request,'index.html',{'articles':articles})

def article_page(request,article_id):
	article=models.Article.objects.get(pk=article_id)
	return render(request,'article_page.html',{'article':article})

def edit_page(request,article_id):
	# article_id=str(article_id)
	if str(article_id)=='0':
		return render(request,'edit_page.html')
	article=models.Article.objects.get(pk=article_id)
	return render(request,'edit_page.html',{'article':article})

def edit_action(request):
	title=request.POST.get('title','TITLE')
	content=request.POST.get('content','CONTENT')
	article_id=request.POST.get('article_id','0')
	if article_id=='0':
		models.Article.objects.create(title=title,content=content)
		articles=models.Article.objects.all()
		return render(request,'index.html',{'articles':articles})
	article=models.Article.objects.get(pk=article_id)
	article.title=title
	article.content=content
	article.save()
	return render(request,"article_page.html",{'article':article})

blog/templates/article_page.html
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset="UTF-8">
	<title>Article Page</title>
</head>
<body>
<h1>{{article.title}}</h1>
<br/>
<h3>{{article.content}}</h3>
<br/><br/>
<a href="{% url 'blog:edit_page' artcle.id %}">修改文章</a>
</body>
</html>

blog/templates/edit_page.html
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset="UTF-8">
	<title>Edit Page</title>
</head>
<body>
<form action="{%url 'blog:edit_action'%}" method="post">
	{% csrf_token %}
	{%if article%}
		<input type="hidden" name="article_id" value="{{article.id}}"/>
		<label>文章标题
			<input type="text" name="title" value="{{article.title}}"/>
		</label>
		<br/>
			<label>文章内容
			<input type="text" name="content" value="{{article.content}}"/>
		</label>
		<br/>
	{% else %}
		<input type="hidden" name="article_id" value="0"/>
		<label>文章标题
				<input type="text" name="title" />
			</label>
			<br/>
				<label>文章内容
				<input type="text" name="content" />
			</label>
			<br/>
	{% endif %}
	<input type="submit" value="提交">
</form>
</body>
</html> 

blog/templates/index.html
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset="UTF-8">
	<title>Title</title>
</head>
<body>
<h1>
	<a href="{% url 'blog:edit_page' 0 %}">新文章</a>
</h1>
{% for article in articles %}
	<a href="{%url 'blog:article_page' article.id%}">{{article.title}}</a>
	<br/>
{% endfor%}
</body>
</html>